name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the Jaeger project! 👋🎉 Thanks for taking the time to fill out this feature request.

        Before you post:
        - Please search for existing issues to avoid creating duplicate bugs/feature requests.
        - Please be respectful and considerate of others (see [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)).
        - If you only have a question, you may get a faster response by asking in [our Slack chat room](https://cloud-native.slack.com/archives/CGG7NFUJ3).
          If you don't have a CNCF Slack account, you may sign up at: https://slack.cncf.io/.

        Additional information helps us troubleshoot the issue faster.
  - type: textarea
    id: requirement
    attributes:
      label: Requirement
      description: What kind of business use case are you trying to solve?
      placeholder: |
        As a [description of a user persona, e.g. Jaeger operator, Jaeger power user]
        I want [functionality]
        so that [benefit].
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: |
        What in Jaeger blocks you from solving the requirement?
        If possible, describe the impact of the problem.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: |
        What do you suggest to solve the problem or improve the existing situation?
        It's ok if you don't have one.
  - type: textarea
    id: questions
    attributes:
      label: Open questions
      description: Questions that should be answered before proceeding with implementation.
