name: test

on:
  # allow running release workflow manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      with:
        submodules: true

    - name: Fetch git tags
      run: |
        git fetch --prune --unshallow --tags

    - name: Fail early if the latest tag is not in semver format
      id: validate-semver
      run: |
        which egrep
        echo v1.50.2 | egrep '^v\d+.\d+.\d+$'

